# Generated by Django 3.2.6 on 2021-10-15 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_puzzle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='created',
        ),
    ]
