# Generated by Django 3.2.6 on 2021-11-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0004_remove_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='image',
            field=models.URLField(default='流出'),
            preserve_default=False,
        ),
    ]
