from puzzle.views.puzzle import PuzzleView
from puzzle.views.account import AccountView
from puzzle.views.brand import BrandView
from puzzle.views.collage import CollageView
from puzzle.views.post import PostView
from puzzle.views.comment import CommentView
from puzzle.views.theme import ThemeView
from puzzle.views.inventory import InventoryView
from puzzle.views.image import ImageView