insert into puzzle_theme (name, created) values ('Ondansetron', '10/21/2020');
insert into puzzle_theme (name, created) values ('Acne Medication 10', '4/8/2020');
insert into puzzle_theme (name, created) values ('Wintergreen Isopropyl Alcohol', '4/6/2021');
insert into puzzle_theme (name, created) values ('homeopathic HCG', '6/18/2020');
insert into puzzle_theme (name, created) values ('Cold Sore Treatment', '9/23/2021');
insert into puzzle_theme (name, created) values ('GAMMAGARD', '12/17/2020');
insert into puzzle_theme (name, created) values ('COMPLERA', '1/12/2021');
insert into puzzle_theme (name, created) values ('Smart Sense Pump Mist', '6/19/2021');
insert into puzzle_theme (name, created) values ('PANCREAZE', '5/14/2021');
insert into puzzle_theme (name, created) values ('Cinnamon Sugar', '1/18/2021');
insert into puzzle_theme (name, created) values ('CVS Chest Rub', '10/24/2020');
insert into puzzle_theme (name, created) values ('VP CH Plus', '4/17/2020');
insert into puzzle_theme (name, created) values ('Gelato APF', '3/10/2021');
insert into puzzle_theme (name, created) values ('Midol', '2/5/2021');
insert into puzzle_theme (name, created) values ('SUYAN CHUNGSYU', '9/3/2020');
insert into puzzle_theme (name, created) values ('NARAMIN', '2/11/2020');
insert into puzzle_theme (name, created) values ('LBEL NATURAL FINISH MOISTURIZING FOUNDATION SPF 25', '9/6/2020');
insert into puzzle_theme (name, created) values ('Perfecting Liquid Foundation Deep Beige', '4/15/2020');
insert into puzzle_theme (name, created) values ('Personal Care Petroleum', '6/2/2020');
insert into puzzle_theme (name, created) values ('Pyridostigmine Bromide', '9/12/2020');
insert into puzzle_theme (name, created) values ('Carbon Dioxide-Oxygen Mixture', '8/24/2020');
insert into puzzle_theme (name, created) values ('Thyme', '6/8/2021');
insert into puzzle_theme (name, created) values ('Pantoprazole Sodium', '6/28/2020');
insert into puzzle_theme (name, created) values ('Lantus', '4/12/2020');
insert into puzzle_theme (name, created) values ('Healing Waters Aloe Cucumber Hand Sanitizer', '5/31/2021');
insert into puzzle_theme (name, created) values ('Breacold Children', '11/21/2020');
insert into puzzle_theme (name, created) values ('benzphetamine hydrochloride', '2/24/2021');
insert into puzzle_theme (name, created) values ('Treatment Set TS340987', '4/17/2020');
insert into puzzle_theme (name, created) values ('Divalproex Sodium', '8/30/2020');
insert into puzzle_theme (name, created) values ('Panrosa Antibacterial Hand With Moisturizers', '1/11/2021');
insert into puzzle_theme (name, created) values ('Mometasone Furoate', '2/1/2021');
insert into puzzle_theme (name, created) values ('Night Time Cherry', '1/5/2020');
insert into puzzle_theme (name, created) values ('SHISEIDO THE SKINCARE TINTED MOISTURE PROTECTION', '1/7/2020');
insert into puzzle_theme (name, created) values ('Levetiracetam', '4/6/2020');
insert into puzzle_theme (name, created) values ('Guinea Pig Epithelium', '8/12/2020');
insert into puzzle_theme (name, created) values ('CENTER-AL - POA PRATENSIS POLLEN', '3/11/2020');
insert into puzzle_theme (name, created) values ('Tussin Cough Long Acting', '9/17/2020');
insert into puzzle_theme (name, created) values ('TERUFLEX Blood Bag System with Diversion Blood Sampling Arm Anticoagulant Citrate Phosphate Dextrose (CPD) AND OPTISOL (AS-5) Red Cell Preservative', '2/25/2021');
insert into puzzle_theme (name, created) values ('Bacitracin Zinc', '5/1/2020');
insert into puzzle_theme (name, created) values ('Lamotrigine', '7/2/2021');
insert into puzzle_theme (name, created) values ('amlodipine besylate and atorvastatin calcium', '1/12/2020');
insert into puzzle_theme (name, created) values ('sunmark ibuprofen pm', '11/20/2020');
insert into puzzle_theme (name, created) values ('Colgate', '4/3/2020');
insert into puzzle_theme (name, created) values ('Oil-Free Acne Wash', '8/16/2020');
insert into puzzle_theme (name, created) values ('Quinapril', '2/16/2021');
insert into puzzle_theme (name, created) values ('Cytotec', '1/26/2021');
insert into puzzle_theme (name, created) values ('Lucky Instant Hand Sanitizer Citrus Zest', '4/22/2021');
insert into puzzle_theme (name, created) values ('Benicar Hct', '11/12/2020');
insert into puzzle_theme (name, created) values ('All-Natural Pen Spray', '9/19/2021');
insert into puzzle_theme (name, created) values ('Brevital Sodium', '12/17/2020');
